const welcomePage = $('.welcome-page')
const mainGameDisplay = $('.main-game-display')

$('.player-name-input').attr('autocomplete', 'off')

$('.submit-players-button').remove('start-game-button-text')

$('.submit-players-button').on('click', domUpdates.submitPlayersName)
$('.spin-wheel').on('click', domUpdates.spinWheel)
$('.spin-wheel').on('click', domUpdates.displayGuessSection)
$('.guess-letter-btn').on('click', domUpdates.comparePlayerInputToAnswer)
$('.guess-letter-btn').on('click', domUpdates.removeGuessSection)
$('.purchase-vowel').on('click', domUpdates.purchaseVowelDisplayChange)
$('.purchase-vowel-btn').on('click', domUpdates.checkPurchasedVowel)
$('.next-player-btn').on('click', domUpdates.showPlayerOptions)
$('.solve-puzzle-option-btn').on('click', domUpdates.displaySolveThePuzzle)
$('.submit-solve-puzzle-guess').on('click', domUpdates.solveThePuzzle)
$('.change-round-btn').on('click', domUpdates.displaySolvedThePuzzle)
$('.incorrect-solve-next-player-btn').on('click', domUpdates.displayIncorrectSolve)
$('.bankrupt-next-player-btn').on('click', domUpdates.displayBankruptMessage)
$('.bankrupt-next-player-btn').on('click', domUpdates.showPlayerOptions)
